language: ruby
jdk:
  - oraclejdk8
sudo: false
rvm:
  - 2.3.1
install:
  - rvm use 2.3.1
  - gem install bundler
  - bundle install
env:
  - TEST_PG_DB_USER=postgres
script: buildr clean package
git:
  depth: 10
