language: java
jdk:


  - oraclejdk7
rvm:
  - 1.9.3
install:
  - rvm use 1.9.3
  - gem install bundler
  - bundle install
env:
  - TEST_PG_DB_USER=postgres
script: buildr clean package
git:
  depth: 10
